version: '3'

networks:
  hydraguide:
    driver: bridge

services:
### PostgreSQL ###########################################
    postgres:
      build:
        context: ./postgres
        args:
          - POSTGRES_VERSION=alpine
      volumes:
        - ./hydra/data/postgres:/var/lib/postgresql/data
        - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_DB=default
        - POSTGRES_USER=default
        - POSTGRES_PASSWORD=secret
      networks:
        - hydraguide
    hydra:
      image: oryd/hydra:v1.9.2
      ports:
        - "4444:4444" # Public port
        - "4445:4445" # Admin port
        - "5555:5555" # Port for hydra token user
      command:
        serve -c /etc/config/hydra/hydra.yml all --dangerous-force-http
      volumes:
        - ./hydra.yaml:/etc/config/hydra/hydra.yml
      environment:
        - DSN=postgres://default:secret@postgres:5432/default?sslmode=disable&max_conns=20&max_idle_conns=4
      restart: unless-stopped
      depends_on:
        - hydra-migrate
      networks:
        - hydraguide

    hydra-migrate:
      image: oryd/hydra:v1.9.2
      environment:
        - DSN=postgres://default:secret@postgres:5432/default?sslmode=disable&max_conns=20&max_idle_conns=4
      command:
        migrate -c /etc/config/hydra/hydra.yml sql -e --yes
      volumes:
        -
          type: bind
          source: ./hydra.yaml
          target: /etc/config/hydra/hydra.yml
      restart: on-failure
      networks:
        - hydraguide

    consent:
      environment:
        - HYDRA_ADMIN_URL=http://hydra:4445
      image: oryd/hydra-login-consent-node:v1.9.2
      ports:
        - "9020:3000"
      restart: unless-stopped
      networks:
      - hydraguide
    keto-migrate:
      image: oryd/keto:latest
      environment:
        - LOG_LEVEL=debug
      command:
        migrate sql postgres://default:secret@postgres:5432/accesscontroldb?sslmode=disable
      restart: on-failure
      networks:
        - hydraguide
    keto:
      image: oryd/keto:latest
      ports:
        - "4466:4466"
      command:
        serve
      environment:
        - LOG_LEVEL=debug
        - PORT=4466
        - DSN=memory
      restart: on-failure
      depends_on:
        - keto-migrate
      environment:
        - DSN=postgres://default:secret@postgres:5432/accesscontroldb?sslmode=disable
      networks:
        - hydraguide
    kratos-migrate:
      image: oryd/kratos:v0.5.5-alpha.1
      volumes:
        - type: bind
          source: ./kratos/email-password
          target: /etc/config/kratos
      command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
      environment:
       - DSN=postgres://default:secret@postgres:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      restart: on-failure
      networks:
        - hydraguide

    kratos-selfservice-ui-node:
      image: oryd/kratos-selfservice-ui-node:v0.5.0-alpha.1
      environment:
        - KRATOS_PUBLIC_URL=http://kratos:4433/
        - KRATOS_ADMIN_URL=http://kratos:4434/
        - PORT=4435
        - KRATOS_BROWSER_URL=http://127.0.0.1:4455/.ory/kratos/public
        - JWKS_URL=http://oathkeeper:4456/.well-known/jwks.json
        - SECURITY_MODE=jwks
      networks:
        - hydraguide
      restart: on-failure

    kratos:
      depends_on:
        - kratos-migrate
      image: oryd/kratos:v0.5.5-alpha.1
      ports:
        - '4433:4433' # public
        - '4434:4434' # admin
      restart: unless-stopped
      environment:
        - DSN=postgres://default:secret@postgres:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
        - LOG_LEVEL=trace
        - SERVE_PUBLIC_BASE_URL=http://127.0.0.1:4455/.ory/kratos/public/
      command: serve -c /etc/config/kratos/kratos.yml --dev
      volumes:
        - type: bind
          source: ./kratos/email-password
          target: /etc/config/kratos
      networks:
        - hydraguide

    mailslurper:
      image: oryd/mailslurper:latest-smtps
      ports:
        - '4436:4436'
        - '4437:4437'
      networks:
      - hydraguide
    oathkeeper:
      image: oryd/oathkeeper:v0.38
      depends_on:
        - kratos
      ports:
        - 4455:4455
        - 4456:4456
      command:
        serve proxy -c "/etc/config/oathkeeper/oathkeeper.yml"
      environment:
        - LOG_LEVEL=debug
      restart: on-failure
      networks:
        - hydraguide
      volumes:
        - ./oathkeeper:/etc/config/oathkeeper
